services:
  processor: # 更明确的语义化名称
    build: ./backend
    image: mri-processor:latest # 保持与之前命名一致
    ports:
      - "5000:5000"
    volumes:
      - "D:/Matlab:/matlab:ro"
      - "D:/spm/spm12:/spm:ro"
      - "mri_data:/app/uploads"
      - "mri_processed:/app/processed"
    environment:
      - MATLAB_ROOT=/matlab
      - LD_LIBRARY_PATH=/matlab/runtime/glnxa64:/matlab/bin/glnxa64
      - CAT12_PATH=/spm/spm12/toolbox/cat12
      - SPM_PATH=/spm/spm12
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mri-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      processor:
        condition: service_healthy
    networks:
      - mri-net

networks:
  mri-net: # 添加专用网络
    driver: bridge

volumes:
  mri_data:
  mri_processed: